const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";

const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";

const NEW_REQUEST="NEW_REQUEST";

//
const NEW_MESSAGE="NEW_MESSAGE";

const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";

const CHAT_JOINED = "START_TYPING";
const CHAT_LEAVED = "STOP_TYPING";

const ONLINE_USERS = "ONLINE_USERS";


export {
    ALERT,
    START_TYPING,
    STOP_TYPING,
    REFETCH_CHATS,
    NEW_ATTACHMENT,
    NEW_MESSAGE_ALERT,
    NEW_REQUEST,
    NEW_MESSAGE,
    CHAT_JOINED,
    CHAT_LEAVED,
    ONLINE_USERS,
}; 